Refactor
DavyJohnes/logrus-yc-hoook pull request #2
Opened 2022-10-14 19:17 UTC by DavyJohnes

2022-10-17 06:07 UTC, positiveviking requested changes

2022-10-17 06:07 UTC, positiveviking commented on hook.go
> +		cancel()
JFYI
```
func New(config Config) (_ *Hook, err error) {
....
  defer func(){
    if err != nil {
      cancel()
    }
   }()
```

2022-10-17 06:07 UTC, positiveviking commented on hook.go
> +		return fmt.Errorf("failed to write log entry: context canceled")
```suggestion
		return fmt.Errorf("failed to write log entry: yc hook closed")
```

2022-10-17 06:07 UTC, positiveviking commented on hook.go
> +		h.entriesCh <- entry
```suggestion
	case h.entriesCh <- entry:
```
here comes race bugs

2022-10-17 06:07 UTC, positiveviking commented on hook.go
> +	if len(h.entriesBuff) > 0 {
```suggestion
	if len(h.entriesBuff) == 0 { return
```

2022-10-17 06:07 UTC, positiveviking commented on hook.go
> +		entriesToSend := h.entriesBuff[:idx]
```suggestion
		entriesToSend := h.entriesBuff
		if len(entriesToSend) > h.config.BufferSize{
			entriesToSend = entriesToSend[:h.config.BufferSize]
		}
```

2022-10-17 06:07 UTC, positiveviking commented on hook.go
> +		case <-h.ctx.Done():
This will happen before all entries will be read from `entriesCh`, ie data loss

2022-10-17 06:07 UTC, positiveviking commented on hook.go
> +			h.entriesBuff = append(h.entriesBuff, entry)
In case of missconfiguration this buffer will grow without limit

In the end of flush buffer should be cleaned

2022-10-17 06:07 UTC, positiveviking commented on hook.go
> +		case <-h.ctx.Done():
i suggest add https://pkg.go.dev/sync#WaitGroup to structure, add call `Add(1)` before running goroutine, in this method add `defer Done()` and add explicit Close method with `h.ctxCancel()` and `Wait()`

2022-10-18 15:57 UTC, DavyJohnes commented on hook.go
> +		cancel()
Ммм... не очень понял, зачем так? У меня ж там единственный случай, когда error может получиться...

2022-10-18 15:57 UTC, DavyJohnes commented on hook.go
> +		entriesToSend := h.entriesBuff[:idx]
Я там еще внизу использую `idx` чтобы отрезать то что отправил в `h.entriesBuff`, так что я бы все оставил в текущем варианте.

2022-10-18 15:57 UTC, DavyJohnes commented on hook.go
> +		case <-h.ctx.Done():
Не понял смысла ждать отправки всех событий в случае отмены контекста.
Если context canceled, то нам надо максимально быстро завершить любую работу с возможным каким-то cleanup'ом. Если контекст отменен, то мы там и ycsdk воспользоваться уже не сможем жею

2022-10-18 15:57 UTC, DavyJohnes commented on hook.go
> +			h.entriesBuff = append(h.entriesBuff, entry)
Так он и так очищается же там https://github.com/DavyJohnes/logrus-yc-hoook/pull/2/files#diff-e6e832ce9eeb51105105595ce823c9b28734de30c345d2b21dddb4b0fa786926R126

2022-10-18 16:34 UTC, positiveviking commented on hook.go
> +		cancel()
Так не забывается в жизненном цикле.

2022-10-18 16:36 UTC, positiveviking commented on hook.go
> +		entriesToSend := h.entriesBuff[:idx]
Много кастов, сложно читать. Копия слайса - не дорого совсем

2022-10-18 16:38 UTC, positiveviking commented on hook.go
> +		case <-h.ctx.Done():
Вот кажется для graceful shutdown надо дождаться окончания отправки.
Иначе накопленное за последние 2с потеряем

2022-10-18 16:39 UTC, positiveviking commented on hook.go
> +			h.entriesBuff = append(h.entriesBuff, entry)
Если отправка свершилась, иначе до упора будет копиться

2022-10-19 18:38 UTC, DavyJohnes commented on hook.go
> +			h.entriesBuff = append(h.entriesBuff, entry)
Предлагаешь ввести максимальный размер и дропать самые старые при его превышении?

2022-10-19 18:40 UTC, DavyJohnes commented on hook.go
> +		case <-h.ctx.Done():
Все еще не понял.
Если контекст отменем, то мы и отправить ничего не сможем, так как `ycsdk` уже закроет соединение, разве нет?

2022-10-19 18:43 UTC, DavyJohnes commented on hook.go
> +		entriesToSend := h.entriesBuff[:idx]
Мне кажется все же вкусовщина. Касты конечно выглядят так себе, но альтернатива - это еще один if.
```
if len(entriesToSend) > h.config.BufferSize { 
  entriesToSend = entriesToSend[:h.config.BufferSize]  
} else {
  entriesToSend = entriesToSend[:0]
}
```

2022-10-19 18:45 UTC, DavyJohnes commented on hook.go
> +		cancel()
Вызываю пояснительную бригаду :)

2022-10-20 06:31 UTC, positiveviking commented on hook.go
> +		entriesToSend := h.entriesBuff[:idx]
Ну нет же, то что в else можно до if присвоить. И вообще зачем такая перемотка?
Тебе надо тут забрать из буфера не больше `BufferSize`, так следом за этим if всегда делай `h.entriesBuff = h.entriesBuff[len(entriesToSend):]` а с количеством ты уже тут разобрался

2022-10-20 06:38 UTC, positiveviking commented on hook.go
> +		case <-h.ctx.Done():
Слава богу нет.
Бывает что используют антипаттерн про контроль sdk внешним контекстом, но тут не сделали такого. В Build контекст передается  потому, что инициализация происходит с сетевыми вызовами. Это способ задать таймаут и иметь возможность прервать инициализацию sdk. То, что ты отдавал в Build не сохраняется после вызова.

Контекст в этом типе - это подобие флажка stopped, только хорошо подходящего для контроля конкуретного выполнения и с идемпотентным присваиваением

2022-10-20 06:40 UTC, positiveviking commented on hook.go
> +			h.entriesBuff = append(h.entriesBuff, entry)
Или при отправке всегда выкидывать порцию, которую начали отправлять.

2022-10-20 06:42 UTC, positiveviking commented on hook.go
> +		cancel()
когда добавишь еще проверку и еще return не будет шанса забыть отменить.
defer очень хорош для действий, который надо обязательно делать при выходе даже если случится паника: unlock, закрытие файлов и тел запросов, отмены контекста.

2022-10-20 18:33 UTC, DavyJohnes commented on hook.go
> +		case <-h.ctx.Done():
Кажется WaitGroup все-таки не нужна, у нас же `flushLogs` не в отдельной горутине делается, иначе говоря в один момент времени только одна `flushLogs` выполняет. Кажется достаточно будет мьютекса.

2022-10-20 18:40 UTC, DavyJohnes commented on hook.go
> +		case <-h.ctx.Done():
Хотя сейчас сам понял что кажется можно все-таки в горутине запускать `flushLogs`.

2022-10-20 18:50 UTC, DavyJohnes commented
@positiveviking обрати внимание, добавил ретраев на отправку.

2022-10-31 14:34 UTC, DavyJohnes commented on hook.go
> +	defer h.entriesBuffMutex.Unlock()
Кажется это плохая идея, надо явно делать unlock перед return'ом

2022-11-17 18:24 UTC, merged